export const LANGUAGE_THRESHOLD = 50;

export const LANGUAGES = [
  "English",
  "Spanish",
  "French",
  "German",
  "Russian",
];

export const COUNTRY_LANGUAGE_DATA = {
  Spain: {
    Spanish: 99,
    English: 35,
    French: 15,
    German: 5,
    Russian: 2,
  },
  Sweden: {
    English: 90,
    Spanish: 5,
    French: 10,
    German: 30,
    Russian: 5,
  },
  Germany: {
    German: 94,
    English: 56,
    Spanish: 8,
    French: 12,
    Russian: 4,
  },
  France: {
    French: 96,
    English: 39,
    Spanish: 10,
    German: 7,
    Russian: 3,
  },
  "United States of America": {
    English: 95,
    Spanish: 42,
    French: 8,
    German: 4,
    Russian: 2,
  },
  Canada: {
    English: 86,
    French: 30,
    Spanish: 6,
    German: 3,
    Russian: 1,
  },
  Mexico: {
    Spanish: 98,
    English: 13,
    French: 5,
    German: 2,
    Russian: 1,
  },
  Brazil: {
    Spanish: 8,
    English: 5,
    French: 4,
    German: 3,
    Russian: 1,
  },
  Argentina: {
    Spanish: 98,
    English: 15,
    French: 6,
    German: 3,
    Russian: 2,
  },
  Russia: {
    Russian: 96,
    English: 12,
    German: 4,
    French: 3,
    Spanish: 1,
  },
  "United Kingdom": {
    English: 98,
    Spanish: 20,
    French: 23,
    German: 9,
    Russian: 2,
  },
  Italy: {
    English: 34,
    Spanish: 12,
    French: 15,
    German: 8,
    Russian: 2,
  },
  Nigeria: {
    English: 79,
    Spanish: 2,
    French: 7,
    German: 1,
    Russian: 1,
  },
  India: {
    English: 12,
    Spanish: 1,
    French: 2,
    German: 1,
    Russian: 1,
  },
  China: {
    English: 10,
    Spanish: 1,
    French: 1,
    German: 1,
    Russian: 1,
  },
  Australia: {
    English: 97,
    Spanish: 10,
    French: 7,
    German: 5,
    Russian: 1,
  },
  "South Africa": {
    English: 36,
    Spanish: 2,
    French: 4,
    German: 2,
    Russian: 1,
  },
};
